### ISSUE TITLE
The engine should raise a syntax error when a complex type is specified instead of one or more of his leaves

### ISSUE THREAD

**Issue by tsunammis** [dailymotion/tartiflette#109]
The engine doesn't raise an error when a complex type is specified as a leaf. We can't have a complex type used as a leaf. 

e.g

```gql
type Query {
  mobility: Mobility
}

type Mobility {
  tramStations(offset: Int, limit: Int): [TramStation]
}

type Location {
  latitude: Float
  longitude: Float
}

type TramStation {
  id: String
  name: String
  line: String
  location: Location
}
```

This following query returns a dict for the location property instead of a *syntax error*.

```gql
query {
  mobility {
    tramStations {
      id
      name
      location
      line
    }
  }
}
```

returns

```json
{
  "data": {
    "mobility": {
      "tramStations": [
        {
          "id": "P2",
          "name": "Place d'Arc",
          "location": {},
          "line": null
        },
        {
          "id": "P4",
          "name": "Patinoire",
          "location": {},
          "line": null
        },
        {
          "id": "P17",
          "name": "Pont de l'Europe",
          "location": {},
          "line": null
        }
      ]
    }
  }
}
```

* **Tartiflette version:** 0.3.4
* **Python version:** 3.7.1
* **Executed in docker:** No
* **GraphQL Schema & Query:** c.f above
* **Is a regression from a previous versions?** No

**Comment by abusi** [comment]
Hum, i'll look at the spec, to found the correct error to raise here. But I think it's pretty logic, you ask for an object whithout asking for a field you get an empty shell ;). Clearly here you have the default value of a non explored object. It should be prettt straight forward to detect during parsing.

If you're out of a field without child and you're not a leaf -> error.

**Comment by abusi** [comment]
for reference : https://facebook.github.io/graphql/June2018/#sec-Leaf-Field-Selections
