### ISSUE TITLE
Question: Status of project

### ISSUE THREAD

**Issue by stevenheidel** [dailymotion/tartiflette#116]
Hi, this is just a question so feel free to close the issue after answering.

How is tartiflette being used at dailymotion curently? Looking at the roadmap: https://github.com/dailymotion/tartiflette#roadmap---road-to-v1 it seems like this project is very close to a v1 release. Is that accurate?

I'm considering whether to use tartiflette for a new project or stick with graphene.

**Comment by tsunammis** [comment]
Hello @stevenheidel 

We are moving fast with **Tartiflette**, and we plan to release it in production next week in a small amount of our traffic _(millions request per hours)_.

The only feature we don't have in this current version is the `subscription` one. [We are working on it, separately](https://github.com/dailymotion/tartiflette/issues/113).

Are you interested in specific features?

We are glad to see you here.

**Comment by stevenheidel** [comment]
Awesome thanks! Millions request / hours is more than my app will see in a long time so it seems like we're good to go.

The main reasons I'm considering tartiflette are:
- First class asyncio support
- Difficulties explaining Graphene to colleagues. I built a sizable app with Graphene-Python and it has a long onboarding time due to the amount of "magic" needed to understand how Graphene maps schemas to classes, etc. and even more magic in graphene-sqlalchemy. Tartiflette looks like it has less magic (exception being how @Resolvers are added implicitly to the schema registry)

**Comment by tsunammis** [comment]
@stevenheidel we are currently focused on:
* The developer experience
* Be fully compliant with the specification

Your feedbacks are precious, do not hesitate if you have any questions.

**Comment by achedeuzot** [comment]
@stevenheidel The magic of `Resolver`s added implicitly to the schema registry is a design decision for a better developer experience. If we wanted to be explicit, we would need to have more boilerplate and we would have to pass around a `SchemaRegistry`-like instance to every `Resolver` which isn't very convenient. We're happy to have your input on it though as having external feedback is very useful to us :)

**Comment by abusi** [comment]
Considering this has answered :). @stevenheidel feel free to report back any bugs, unsupported features and any others improvement you find/need.
Happy to have other people using it :).
