### ISSUE TITLE
Documentation site Navigation menu label not very visible

### ISSUE THREAD

**Issue by nicoferron** [dailymotion/tartiflette#149]
Hello,

On the documentatioin site with a small width screen, in the nav bar, the inactive labels are not very visible (white on light blue):
![capture du 2019-03-08 14-33-31](https://user-images.githubusercontent.com/42807850/54031507-396c6c80-41af-11e9-8734-ddfb6a0afbff.png)

Cheers,

**Comment by tsunammis** [comment]
We fixed it.

<img width="930" alt="Screenshot 2019-03-12 at 14 18 11" src="https://user-images.githubusercontent.com/158689/54203069-b9f1dc80-44d1-11e9-8e27-23a3f4f474b4.png">

**Comment by nicoferron** [comment]
Wonderful
