### ISSUE TITLE
Add an "Edit on GitHub" link on the docs

### ISSUE THREAD

**Issue by florimondmanca** [dailymotion/tartiflette#165]
## Request a feature

* A part of the project could be improved

Hi! First, I'm very excited about Tartiflette, especially because it's async-first and quite Pythonic on the outside, so thanks for this project.

I am following along the [recipes manager tutorial](https://tartiflette.io/docs/tutorial), and noticed typos in several places, be it in text copy or in code snippets.

I read the contributing guidelines and tbh having to fork, clone, and lint everything in order to send a simple typo fix seems kind of overkill / way to high a barrier.

Hence, I'm wondering if you guys could incorporate a "Edit on GitHub" link to the docs. I believe this would allow more people to help improve the docs. :-)

**Comment by abusi** [comment]
On tartiflette.io (https://tartiflette.io/docs/tutorial/getting-started) you have the "Edit" button on top of each page that will help you do that @florimondmanca.
If I have clearly understood your request?

**Comment by abusi** [comment]
We would greatly liked to have typos fixed if you found some. Also If you found something that isn't really clear or not working, don't hesitate to report it here.

**Comment by florimondmanca** [comment]
OK, my bad. I didn't see that "Edit" button. 🤦‍♂️ Thanks for the prompt reply!

I guess that's because I'm used to have the edit link being at the bottom of the page.

Two suggestions that I leave to your appreciation:
1. Duplicate the link at the bottom of the page?
2. Add an "edit" icon along with the text, e.g. ✏️?

Anyway, now that I have it I'll send fixes through. :-)

**Comment by florimondmanca** [comment]
I ended up forking the repo anyway because the change is multi-file.

How can I run the docs site locally to preview the changes? :blush: I don't see any `make docs` or `make build` target in the `Makefile`, and I didn't see particular instructions in the contributing guide.

**Comment by abusi** [comment]
@florimondmanca I think you can't yet.
@tsunammis do you have an idea here?
https://github.com/dailymotion/tartiflette.io contains the code of the website, it's this project that will deploy the pages from the file in this repository master branch.
I think that tinkering with a copy of this repo, you'll be able to spawn the "tartiflette.io" locally.

**Comment by tsunammis** [comment]
Hello @florimondmanca 

Thank you for your contributions to tartiflette, we are glad to see you here.

> Duplicate the link at the bottom of the page?

We will add a link at the bottom of the page, it will be easier for the contributor to find the edit link. 👍 

> How can I run the docs site locally to preview the changes? 😊 I don't see any make docs or make build target in the Makefile, and I didn't see particular instructions in the contributing guide.

You're right, this is not straightforward to preview your changes from the tartiflette repository. We have to add a new makefile target to clone and launch the tartiflette.io website locally and help you get a preview.

**Comment by tsunammis** [comment]
@florimondmanca you are now able to launch the documentation website locally by executing `make run-docs`.

Is it what you expected?

**Comment by florimondmanca** [comment]
Sounds good! Will test it out shortly.

**Comment by florimondmanca** [comment]
@tsunammis Works great! The hot reload is very helpful. Thanks! :+1:
