### ISSUE TITLE
"Pythonicity" suggestions

### ISSUE THREAD

**Issue by florimondmanca** [dailymotion/tartiflette#169]
Hi,

This isn't a bug report nor a feature request. Pardon in advance if this comes up as controversial: this is about style, naming conventions and how "Pythonic" Tartiflette is.

### Decorator casing

I noticed that most decorators (resolvers, subscriptions, directives) are `PascalCase`.

Since [functions should be named using snake case](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names), and decorators are just functions that return other functions, `@Resolver`, `@Directive`, `@Subscription` et. al. came as a surprise to me. I understand they may be classes (I didn't look up the code), but it does feel unpythonic to me. In fact seeing pascal-cased decorators feels reading PHP or TypeScript code.

What would you think of exporting aliases such as `resolver` or `directive`?

### Lack of verbs in resolver functions

In the documentation, resolver functions are named exclusively with names, e.g. `hello_resolver()` or `resolver_hello()`.

My experience of reading tens of thousands of lines of Python code inclines me towards the belief that functions should start with a verb, unless using names is shorter or increases readability.

I wasn't able to find any official recommendation for this, but Brandon Rhodes agrees on this in [this talk](https://www.youtube.com/watch?v=YklKUuDpX5c&frags=pl%2Cwn) (12:43: "for stuff that does something, use a verb — explicit is better than implicit").

Anyway, so my suggestion would be to switch from say `hello_resolver()` to `resolve_hello()`, and `subscription_cooking_time()` to `subscribe_cooking_time()` (or perhaps `on_cooking_time()` if if better fits how and when subscription functions are called).

The good thing is that this should mostly be a documentation change instead of a library code change.

FYI, this is how Graphene does things:

```python
class Query(graphene.ObjectType):
    hello = graphene.String(description='A typical hello world')

    def resolve_hello(self, info):
        return 'World'
```

---

Ultimately this is probably nit-picking, but one thing I am convinced of is that some (most?) Python devs would prefer to use a pythonic library over a non-pythonic one, so I think it's important in terms of making Tartiflette embrace the community and attract more users.

Tartiflette seems sufficiently young that I figured raising these issues up was relevant.

Happy to read your thoughts on this!

**Comment by abusi** [comment]
I agree that resolver naming is a documentation problem, as the implementation only asks that the decorated objet been asyncally callable and takes 4 unnamed arguments.

On the philosophy of naming function, i'd like to name function using verbs if they are member of a class, and i'm inclined to think of them as object naming them by answering the 'what it is ?' question if they are not.

@tsunammis what's your take on this ?

For the decorator, they are defined as callable classes, thus they are Capitalized.

Thank you for this issue, it's in these early stages that we can rectify things like that ;)

**Comment by florimondmanca** [comment]
Thanks for your answer!

> On the philosophy of naming function, i'd like to name function using verbs if they are member of a class, and i'm inclined to think of them as object naming them by answering the 'what it is ?' question if they are not.

I understand the "what is it?" approach. Yet, I've seen the opposite (name functions using verbs only if they're not members of a class) be done more often. The `obj.method()` syntax already feels a lot like `name.verb()` that we can spare having to put a verb in the method name. Plus the parentheses help understand it’s a function call that "does something". Okay, maybe this is debatable.

But on the other hand, functions that are not members of a class don’t have any other context to help understand *what they do*, which is IMO why they should be named with a verb: `create_item()` instead of `item()`, or `resolve_hello()` instead of `hello_resolver()`.

We're actually fine here because resolvers are declared once and never used again. In general though, naming a function with names prevents from storing the return value of that function as that name. For example, a `connection()` function would prevent from storing the returned connection as `connection`, which is the most readable name, and use less readable names like `conn`.

So my point is that even though we're fine in practice, general principles should still apply and resolver functions should be named with verbs.

> For the decorator, they are defined as callable classes, thus they are Capitalized.

Yes, that’s what I was expecting. :) The thing is that although a decorator is *implemented* as a class because its behavior is quite complex, a lot of the times in Python it is *aliased* or *wrapped* around a function. Sometimes even, class naming convention is dropped altogether by naming the class in snake case. These patterns can be seen all over the standard library (although the std lib not a model of naming consistency):
- `contextlib.contextmanager` is a function whose implementation is delegated to a class named `_GeneratorContextManager`.
- `functools.partial` is actually a class.

So I kindly reiterate my suggestions with the main motivation that, if we conceed that there are certain naming conventions that make a piece of code more or less *pythonic*, how pythonic a library is can make or break its attractiveness. Of course I’ll respect your decision if you prefer to keep things like they are.

**Comment by tsunammis** [comment]
Hello @florimondmanca 

Thank you for your contributions, your comments are really valuable for us and the tartiflette community 👍  

## Decorator casing

You're right, we use the `PascalCase` mainly because the underlying piece of code behind are classes.

Your idea of adding aliases like `resolver`, `directive` and `subscription` seems interesting. We will add this issue to our to-do list 👍 (#172)

## Use verbs in resolver methods name

To be more understandable and close to the pythonic mindset, we will update the naming of the `resolvers` methods name, based on your suggestions. Even thus, I agree with @abusi that this part is a documentation issue. 

Thank you for catching up this issue, with these improvements, we will be closer of the `zen of python` mindset.

Have a nice evening

**Comment by tsunammis** [comment]
@florimondmanca Here is a pull-request which integrate your suggestions regarding the methods naming. What do you think? -> https://github.com/dailymotion/tartiflette-aiohttp-tutorial/pull/1

**Comment by tsunammis** [comment]
A pull request has been merged with your advice and an issue created to handle the `snake_case` version of the decorators.

Do not hesitate if you think that this issue is not solved
