### ISSUE TITLE
Provide snake-case aliases for `Subscription`, `Resolver` and `Directive`

### ISSUE THREAD

**Issue by tsunammis** [dailymotion/tartiflette#172]
As suggested by @florimondmanca here #169. It should be more pythonic to expose snake-case aliases for `Subscription`, `Resolver` and `Directive`.

- [ ] Pull-request for the tartiflette implementation
- [ ] Pull-request for the documentation
- [ ] Pull-request for [the tutorial](https://github.com/dailymotion/tartiflette-aiohttp-tutorial)

**Comment by tsunammis** [comment]
Hello @florimondmanca,

The current tree of the `tartiflette` module contains a submodule called `resolver` and `directive`. Which doesn't allow us to expose the snake-case aliases of `Directive` and `Resolver`.

We agree with your point of view, we will add this improvement to a future major version.

**Comment by florimondmanca** [comment]
Understood! If this requires breaking chances, I can see why this shouldn’t make it to Tartiflette for now.

**Comment by florimondmanca** [comment]
Hey @tsunammis, is this issue still considered for a future major version despite being closed? Perhaps this should be reopened unless this is something we won't consider implementing in the future at all?

Also, I think sub-packages conflicting with the snake-cased decorators can be easily worked around (e.g. by renaming packages to `resolvers` and `directives`).
