### ISSUE TITLE
Switch from Pylint to Black

### ISSUE THREAD

**Issue by singingwolfboy** [dailymotion/tartiflette#175]
[Pylint](https://pylint.org/) and [Black](https://black.readthedocs.io) are two projects that do very similar things: tell you how to format your Python code. Personally, I prefer Black -- but I understand that not everyone does. I'm raising this issue to open a discussion on whether Tartiflette should switch from Pylint to Black.

## Why [Black](https://black.readthedocs.io) is Better
- No configuration, no options, which also means no wasting time discussing which way to configure it. Black is highly opinionated.
- Black will automatically reformat your code. Pylint will only complain about it and expect you to fix it.

## Why [Pylint](https://pylint.org/) is Better
- Black _only_ does code formatting. Pylint warns about all sorts of things, ranging from code formatting to cyclomatic complexity to number of arguments for a method and beyond.
- Black is a very young project (it's still in beta!) while Pylint has been around for a long time.

**Comment by tsunammis** [comment]
Hello @singingwolfboy 

Thank you for your issue. As you may already noticed, we use both of them. `black` to format and `pylint` in addition. According to me, they are complementary, maybe in the future `black` will be sufficient.

https://github.com/dailymotion/tartiflette/blob/master/setup.py#L56

Overview 
```python
_TEST_REQUIRE = [
    "pytest==4.1.1",
    "pytest-cov==2.6.1",
    "pytest-asyncio==0.10.0",
    "pytest-xdist",
    "pylint==2.3.0",
    "xenon",
    "black==18.9b0",
    "isort==4.3.4",
]
```

**Comment by singingwolfboy** [comment]
Oh! I don't know how I missed that. 😅 Well, I'm glad this project is using Black! I'll close this issue, since it seems there's nothing to discuss or do.

**Comment by tsunammis** [comment]
@singingwolfboy no worries ;-)

thank you!
