### ISSUE TITLE
Simplify resolver signature

### ISSUE THREAD

**Issue by florimondmanca** [dailymotion/tartiflette#221]
## Request a feature

* [x] A part of the project could be improved?

*This would be a breaking change.*

Suppose the following query:

```graphql
Query {
    hello(name: String): String
}
```

Currently, a typical resolver looks like this, i.e. a function with 4 positional arguments:

```python
@Resolver("Query.hello")
async def resolve_hello(parent, args, ctx, info):
    name = args["name"]
    return f"Hello, {name}!"

```

Here's my : I think **4 positional arguments is too much**. While typing the example above, I had to stop and try to remember what were the 4 arguments I had to give to `resolve_hello`. I ended up looking the docs. Click (the Python CLI library) has a similar problem: callbacks use 3 positional arguments, which sometimes require me to look up their order and names (not even mentioning the fact that the signature has changed between versions).

For all these reasons, I would suggest **lowering the number of arguments to just 2**: `parent` and `info`.

This would allow to rewrite the above resolver like this:

```python
@Resolver("Query.hello")
async def resolve_hello(parent, info, name: str = None):
    return f"Hello, {name}!"
```

Or even shorter:

```python
@Resolver("Query.hello")
async def resolve_hello(*_, name: str = None):
    return f"Hello, {name}!"
```

Here's what changes:

- Query arguments are passed as keyword arguments.

This would allow to explicitly define what arguments the resolver takes on the Python side, and add type annotations to make things extra clear (like above). We could also indicate that the argument is required by dropping `= None`. The current `args` interface doesn't allow any of that.

In terms of implementation, we essentially just have to pass `**args` to the resolver instead of `args`.

(Also, I read in the [docs](https://tartiflette.io/docs/api/resolver#function-signature) that "this signature is highly inspired by the GraphQL.js implementation": I *think* passing arguments as an object is the JS way to implement Python-like keyword arguments, because they have object destructuring, e.g. `hello(args)` can be rewritten as `hello({ name })`. So it's very convient for JS devs, but I guess not so much for Pythonistas.)

- The context is accessible as `info.context`.

The docs about [the `info` resolver argument](https://tartiflette.io/docs/api/resolver#resolver-info-argument) read that it "can be useful for middlewares and advanced use-cases". My concern is that for 95% of users — who just need to use query arguments and the `context` — this makes `info` useless and turns it into boilerplate.

So, since it's supposed to contain data related to query execution, why not have it contain `ctx` too? This would make it useful to *everyone*. Besides, typing `foo = info.context["foo"]` is similar in effort to `foo = context["foo"]`.

**Comment by tsunammis** [comment]
Hello @florimondmanca 

## Why the `(parent, args, ctx, info)` signature?

When we started to work on tartiflette, we wanted to minimize the impact on our legacy codebase built on top of graphene. Our codebase is made of tons of resolvers which respect this signature, to be compliant both with tartiflette and graphene.
I agree with you that this is not perfect. A step back is necessary to understand the reasons for this choice.

To be honest, we don't plan to change the signature during the next 6 months. Currently, our team is currently focused on working on the extensibility of the library (through the Directive for instance). To be transparent, we started to work on 2 big topics:
- [Extensibility through @directive hook's specification](https://github.com/dailymotion/tartiflette/issues/224)
- [Improve query parsing and validation](https://github.com/dailymotion/tartiflette/issues/121)

Once these topics will be developed, it will allow developers to contribute to tartiflette by providing some interesting `directives`, `types`, `scalar` and so on.

**Comment by florimondmanca** [comment]
Thanks for the explanation and the historical context @tsunammis.

I understand there's already a ton of code at DM that uses this signature. However, do you think supporting *both* signatures (by inspecting them) would be a viable mid-term solution?

My rough intuition is that this could be implemented by replacing:

```python
await resolver(parent, args, context, info)
```

with:

```python
try:
    await resolver(parent, args, context, info)
except TypeError:
    info = dict(info, context=context)
    await resolver(parent, info, **args)

```

where resolvers are called.

As far as I understand how try/except works in Python, this would have 0 performance impact when using the current signature (i.e. DM's current use case), and it would allow to use a simplified signature right away.

My concern is then how to make these 2 styles live together in the docs without making it confusing.

(Also — thanks for opening the discussion about the directive API!)

**Comment by abusi** [comment]
If my field takes more than 3 parameters, like:
```graphql
type Ninja {
     availableWeapons(first: Int!, limit: Int!, filters: [String!], orderBy: OrderEnum): Weapons
}
```

```python
@Resolver("Ninja.availableWeapons")
async def the_resolver_of_ninja_available_weapons(parent_result, ctx, info, first, limit, orderBy, filter=None): 
        # do things
```
Here my resolver has to many parameters for default pylint to be happy, and this is a basic example. I'm sure we can find use cases needing more than 4 parameters. So to solve this, your going to have `**kwargs` in you resolver, and do `kwargs.pop(p, default)` and manage edge case for each parameters which is equal to have a prototype as `(pr, args, ctx, info)` which has the advantage of never be more than 4 parameters, are always the same, and so on, nothing goes against the resolver doing: 
```python
@Resolver("X")
@Resolver("Y")
....
async def a_generic_resolver(pr, args, ctx, info):
           # manage graphql/transport/errors logic if needed with ctx and info 
         return await do_the_business(pr, **args) # call the business side of the code
```  
With this kind of construct you can generalize the "graphql" logic of your business and Tartiflette stays generic.

I hope this helps you to better see why we did this.

**Comment by florimondmanca** [comment]
Hmm, yes, I see how there’s a scaling issue associated to having more and more GraphQL parameters. Thanks @abusi.

I’m less and less convinced a new signature  (probably with too much magic) is a good idea. I think we can close this. Thanks for discussing!

**Comment by abusi** [comment]
Thanks you for raising your concerns, please continue to do so. There plenty of point in the Tartiflette implementation that needs this kind of questionning, it's very constructive for us to have an external POV.

**Comment by florimondmanca** [comment]
Sure, anytime! 👍

**Comment by tsunammis** [comment]
Thank you @florimondmanca 👍
