### ISSUE TITLE
Miscellaneous Questions

### ISSUE THREAD

**Issue by syrusakbary** [dailymotion/tartiflette#32]
First of all, I'm impressed by the amount of effort and code quality this project has. So congrats to all team that has worked towards that 👏 

After setting up the project locally and trying it, I think there are some things that Graphene and GraphQL-core can learn from it, especially regarding Developer Experience generating the schema from SDL.

## Questions
However, I have some questions that I would love to know the reasoning behind it:
* This project almost clones all the type definitions necessary to have the GraphQL schema running. Most of this definitions are already existing in GraphQL-core, so I wonder what was the reason to duplicate the effort here (shouldn't be easier to at least reuse the data structures?). If the goal was to provide a much faster execution model, now there are better ways to do it in graphql-core (with custom `backend`).
* For running a GraphQL query, the AST has to be re-visited at runtime for each Query. (Similar thing happens for GraphQL-core but it's quite optimized in [Quiver](https://graphql-quiver.com/)) Do you think this will alleviate performance issues?
* A schema is mutable, so resolvers can be attached after the fact of schema creation. GraphQL-core implementation of schemas are immutable (as same as any other definition), this is a great pattern to avoid parallelism issues and other nice things. But I'm curious to know if there are more reasonings (apart of plugging resolvers after schema creation) for a mutable schema.
* All resolvers are async. Running everything in an event loop introduces significant overhead, why run in the event loop if the function can be resolved synchronously?

## Benchmarking

This project also aims to be focused on performance first. However, after benchmarking some cases (such as the supported introspection query, and a hello world), the results are not much better than with GraphQL-core.

And here are the results (mean values):
* Full Introspection Query: 8ms with Tartiflette / 6ms with Cached AST in GraphQL-core / 150us Quiver
* Hello world Query: 240us (0.24ms) Tartiflette / 400us (0.4ms) GraphQL-Core / 12us Quiver

### Tartiflette

Here is a snippet of how I benchmarked a Hello world query with Tartiflette:

```python
def test_tartiflette_execute_basic_type_introspection_output(benchmark):
    schema_sdl = """
    type Query {
        hello: String
    }
    """

    ttftt = Tartiflette(schema_sdl, serialize_callback=lambda x: x) # So we don't add json-encoding overhead

    @Resolver("Query.hello", schema=ttftt.schema)
    async def func_field_resolver(*args, **kwargs):
        return "World"

    ttftt.schema.bake()

    async def execute():
        result = await ttftt.execute("query { hello }")

    loop = get_event_loop()
    from asyncio import Event, ensure_future

    def execute_async():
        loop.run_until_complete(execute())

    p = benchmark(execute_async)
```

### GraphQL-core

```python
def test_benchmark_graphql_core(benchmark):
    from graphql import (
        GraphQLSchema,
        GraphQLObjectType,
        GraphQLField,
        GraphQLString,
        GraphQLCoreBackend,
    )

    # from graphql_quiver import GraphQLQuiverBackend

    def func_field_resolver(*args, **kwargs):
        return "World"

    Query = GraphQLObjectType(
        "Query",
        fields={"hello": GraphQLField(GraphQLString, resolver=func_field_resolver)},
    )

    schema = GraphQLSchema(Query)
    backend = GraphQLCoreBackend()
    # backend = GraphQLQuiverBackend()
    document = backend.document_from_string(schema, query)

    def execute():
        result = document.execute()
        # print(result.data)

    loop = get_event_loop()

    def execute_async():
        loop.run_until_complete(execute())

    p = benchmark(execute)
    # execute_async()
```

I would love to join efforts together, especially regarding things that can be reused across projects, so companies don't duplicate efforts towards the same goals.

If possible, I would love to jump into a talk and chat about it :)

Keep up the good work!

**Comment by tsunammis** [comment]
Hi syrus :)

Thanks for the testing & feedback. Here are some answers to some of the questions and miscellaneous remarks.

First off, please bear in mind that the current implementation is still under heavy development: many things are expected to change in the coming weeks as we're still exploring and trying out various options. Benchmarking the framework now has little meaning as pretty much everything is expected to change in the following weeks.

Now, about your questions:

  * It's true some type definitions are similar to GraphQL-core, but as many things are still under heavy development we need this flexibility to try out things. We also expect some of these type definitions to be tightly integrated with the execution engine which might not be as straightforward with GraphQL-core.
  * We expect to add many layers of optimizations on the current tartiflette engine so most probably we'll find ways to reduce this.
  * We haven't fixed the immutability vs mutability subject yet as we're still changing many things. I guess this will depend on performance and developer experience.
  * This comes from our experience running GraphQL under high traffic and with the fact that most of our resolvers are asynchronous to work with our micro-services architecture.

Finally, we're always happy to discuss this once our framework will be stabilized :)

**Comment by achedeuzot** [comment]
Closing this for now.

**Comment by jedie** [comment]
I noticed Performance issues with large data sets with graphene, too: https://github.com/graphql-python/graphene/issues/268
So i test tartiflette by making a small benchmark and compare with graphql-core...

But I am surprised that **tartiflette** (~57ms) is even significantly slower than **graphql-core** (~20ms).

My benchmark code:

**tartiflette**: https://gist.github.com/jedie/45ddf8ee7e24704c9485eb8cbcf9ba13
**graphql-core**: https://gist.github.com/jedie/581444e02e784ff7c2b9fb1e763759fa

Any comments?
