### ISSUE TITLE
Low-hanging fruits

### ISSUE THREAD

**Issue by piotr-yuxuan** [dailymotion/tartiflette#51]
Hello, thanks for this amazing project 👋 Would you mind spot some simple, easy bugs for new-comers to ramp up with them?

**Comment by tsunammis** [comment]
@piotr-yuxuan Hello! Sorry for the delay, I was off for holidays. 
Thus, we didn't list bug yet to helping people to ramp up with the library. We will work on it next week!
Thank you!

**Comment by brasilikum** [comment]
Same here, how about a 'beginner friendly' tag on the issues?

**Comment by tsunammis** [comment]
thank you @brasilikum! We don't have (yet) that kind of issue.

In the future, we will flag the issues with the **good first issue** label for these which will be interesting for newcomers.

**Comment by tsunammis** [comment]
Hello @brasilikum and @piotr-yuxuan 
We have our "good first issue" if you are interested -> https://github.com/dailymotion/tartiflette/issues/179

**Comment by brasilikum** [comment]
I guess with the label in place this issue can be closed

**Comment by tsunammis** [comment]
Thank you !
